# Generated by Django 4.2.29 on 2026-06-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_userprofile_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
    ]
