# Generated by Django 4.2.29 on 2026-07-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
