# Generated by Django 4.2.29 on 2026-07-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_category_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="Display this product on the homepage of the featured product",
            ),
        ),
    ]
