# Generated by Django 4.2.29 on 2026-07-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_cart_alter_wishlist_created_at_cartitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wishlist",
            options={"ordering": ["id"]},
        ),
    ]
