# Generated by Django 4.2.29 on 2026-07-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_wishlist_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True, editable=False, max_length=20, unique=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="customer_id",
            field=models.CharField(
                blank=True, editable=False, max_length=20, unique=True
            ),
        ),
    ]
