# Generated by Django 4.2.29 on 2026-07-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_order_order_number_userprofile_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
