# Generated by Django 4.2.29 on 2026-07-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="customer_id",
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
