# Generated by Django 4.2.29 on 2026-07-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_userprofile_customer_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total_Price",
            new_name="total_price",
        ),
    ]
