# Generated by Django 4.2.29 on 2026-07-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_rename_total_price_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True, editable=False, max_length=20, unique=True
            ),
        ),
    ]
