# Generated by Django 4.2.29 on 2026-08-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_alter_order_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tx_ref",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
